service: serverless-ts-sample

plugins:
  - serverless-webpack
  - serverless-layers

custom:
  serverless-layers:
    layersDeploymentBucket: serverless-ts-sample-lambda-layers

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x

package:
  # S3にアップロードしてくれる際に除外
  exclude:
    - node_modules/**
    - migrations/**
    - .git/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
